name: "Pull request build"
on:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ubuntu-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-m2
      - name: Build with Maven
        run: mvn clean install
